### ISSUE TITLE
Metadata for files other then PNG

### ISSUE THREAD

**Issue by tester0077** [fhmwg/current-tags#12]
In my own experience, my data files include several formats other than JPGs.

The current normative spec includes recommendations to write/work with several metadata fields, including EXIF specific ones.

As I read the document right now, it seems to oriented entirely towards JPG images because its recommendations for EXIF fields do not include any mention of the possibility that these fields might not be available.

Could I suggest that you also consider images or data files for which their specs do not provide for EXIF data, such as at least PNGs or PDFs.

EXIF data for PNGs are only covered by recent amendments to the PNG standards and many utilities and/or libraries neither read, display or write to PNG EXIF fields.

For PDFs, my current understanding is that the PDF spec do not include EXIF data specifically, though some specs include XMP data.

**Comment by tychonievich** [comment]
The XMP standard we built on (we didn't use EXIF in part because of the reasons you noted) are defined for many file formats. I've tested it with AIF, GIF, HEIC, HEIF, JPEG, PNG, SVG, TIFF, and WEBP. In principle it should also work with other formats, but I haven't tested them yet.
